### ISSUE TITLE
Move recent changes up in the minigame hud

### ISSUE THREAD

**Issue by TimOosterom** [hex-agon/volcanic-mine-stability-tracker#1]
![image](https://user-images.githubusercontent.com/9056584/183311985-15e92a36-f9a6-47b0-ba7e-a5394001ff71.png)

I believe it's just moving it up in the hud component here:
https://github.com/hex-agon/volcanic-mine-stability-tracker/blob/538ebc80065d4d99c84bb06ac0516c4d1f00314c/src/main/java/fking/work/vmtracker/VolcanicMineTrackerPlugin.java#L20

I can't build runelite right now or I'd have tested it myself and made a pr; I'll test/do this tomorrow if needed regardless

**Comment by hex-agon** [comment]
Fixed in #2
